[project]
name = "nlp-news-thai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "datasets>=4.5.0",
    "deepcut>=0.7.0.0",
    "gensim>=4.4.0",
    "ipywidgets>=8.1.8",
    "jupyterlab>=4.5.5",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "pip>=26.0.1",
    "pyldavis>=3.4.1",
    "pythainlp>=5.2.0",
    "python-crfsuite>=0.9.12",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "sentencepiece>=0.2.1",
    "spacy>=3.8.11",
    "tqdm>=4.67.3",
    "transformers>=5.2.0",
]

[project.optional-dependencies]
cpu = [
  "torch>=2.9.1",
  "tensorflow>=2.20.0",
]
cu126 = [
  "torch>=2.9.1",
  "tensorflow[and-cuda]>=2.20.0",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu126" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu126", extra = "cu126" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
